name: Browserstack TED Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  execute_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }}" >> .env
          echo "BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}" >> .env
          echo "GH_ACTIONS_RUNNER=${{ github.run_number }}" >> .env

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Execute Tests
        run: poetry run robot -d reports .

      - name: Generate Report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}